# Generated by Django 5.2.10 on 2026-01-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='source',
            field=models.FileField(blank=True, null=True, upload_to='videos/source/'),
        ),
    ]
