# Generated by Django 5.2.10 on 2026-01-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_video_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.FileField(default=2, upload_to='videos/source/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
